### ISSUE TITLE
Eigen3 error

### ISSUE THREAD

**Issue by PieterWaelbers** [hiwad-aziz/ros2_occupancy_grid#1]
When building the following error occurs.
error: static assertion failed: FLOATING_POINT_ARGUMENT_PASSED__INTEGER_WAS_EXPECTED
  740 |       EIGEN_STATIC_ASSERT(bool(NumTraits<T0>::IsInteger) &&
      |                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
  741 |                           bool(NumTraits<T1>::IsInteger),
      |                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  
/usr/include/eigen3/Eigen/src/Core/util/StaticAssert.h:33:54: note: in definition of macro ‘EIGEN_STATIC_ASSERT’
   33 |     #define EIGEN_STATIC_ASSERT(X,MSG) static_assert(X,#MSG);
      |                                                      ^
Is there a fix for this?
Kind regards!

**Comment by hiwad-aziz** [comment]
Hey @PieterWaelbers, this issue should be fixed with the latest commit (https://github.com/hiwad-aziz/ros2_occupancy_grid/commit/e6f236683d299f8d916713f8c3e418f57949d046).
